### ISSUE TITLE
Manifest should specify a minimum API level

### ISSUE THREAD

**Issue by kpcyrd** [BerlinMeshnet/cjdns-android#5]
In file AndroidManifest.xml

```
Manifest should specify a minimum API level with <uses-sdk android:minSdkVersion="?" />; if it really supports all versions of Android set it to 1.
```

**Comment by benhylau** [comment]
The new Toolbar-based ActionBar implementation supports all the way down to API 7. I think there are some other things used that requires API 11, but I think API 11 is a reasonable baseline requirement.

By the way, the min and target SDK levels are now specified in the **build.gradle**, which overrides what's in the **AndroidManifest.xml**.

**Comment by benhylau** [comment]
Should we close this issue?

**Comment by lgierth** [comment]
Go ahead and do it, I invited you to the org

**Comment by benhylau** [comment]
Cool, thanks for the invite :smile:
