### ISSUE TITLE
Get it on F-Droid

### ISSUE THREAD

**Issue by deavmi** [BerlinMeshnet/cjdns-android#61]
It would help a lot if you could get the app on F-Droid (at f-droid.org).

**Comment by ghost** [comment]
Yes, thanks! We know...

**Comment by ghost** [comment]
Sorry, that sounded harsher than it was intended to. It's just that we already have this other identical issue which you obviously noticed since you commented on it... ;)

**Comment by deavmi** [comment]
Yeah, I noticed it afterwards. I was being pushy. Sorry.

**Comment by deavmi** [comment]
>  that sounded harsher 

Not at all. :)
