### ISSUE TITLE
Is this alive?

### ISSUE THREAD

**Issue by jaredallard** [BerlinMeshnet/cjdns-android#68]
What's the status of this project? I'd love to see what can be done, help out, and possibly back this with $$$ if needed as well. We use cjdns where I work, and having access to stuff on Android would be cool.

**Comment by benhylau** [comment]
If you build from this branch it should set up a VPN service to some hardcoded peers: https://github.com/hyperboria/android/tree/develop#installation

The code is in an unpleasant state to work with unfortunately. I do intend to get back on this towards end of year.

**Comment by jaredallard** [comment]
@benhylau Awesome, I asked mostly because I can't even get cjdns to build right now and It's pretty hopeless for me, a non C/C++ dev :( 

Thanks for the commitment!

**Comment by benhylau** [comment]
You mean the cross-build for ARM? It actually clones from a fork I haven't had time to clean up and upstream and runs this `android_do` script that @sssemil wrote: 

https://github.com/hyperboria/android/blob/develop/build.gradle#L26-L39
https://github.com/benhylau/cjdns/blob/master/android_do
