### ISSUE TITLE
Can't build binaries

### ISSUE THREAD

**Issue by vikulin** [BerlinMeshnet/cjdns-android#75]
This error reroduces in develop branch:

root@gem-01:~/android# ./install_debug
./install_debug: 3: ./install_debug: ndk-build: not found
Starting Build
Settings evaluated using settings file '/master/settings.gradle'.
Projects loaded. Root project using build file '/root/android/build.gradle'.
Included projects: [root project 'android']
Evaluating root project 'android' using build file '/root/android/build.gradle'.
Creating configuration compile
Creating configuration apk
Creating configuration provided
Creating configuration wearApp
Creating configuration annotationProcessor
Creating configuration androidTestCompile
Creating configuration androidTestApk
Creating configuration androidTestProvided
Creating configuration androidTestWearApp
Creating configuration androidTestAnnotationProcessor
Creating configuration testCompile
Creating configuration testApk
Creating configuration testProvided
Creating configuration testWearApp
Creating configuration testAnnotationProcessor
Creating configuration debugCompile
Creating configuration debugApk
Creating configuration debugProvided
Creating configuration debugWearApp
Creating configuration debugAnnotationProcessor
Creating configuration testDebugCompile
Creating configuration testDebugApk
Creating configuration testDebugProvided
Creating configuration testDebugWearApp
Creating configuration testDebugAnnotationProcessor
Creating configuration releaseCompile
Creating configuration releaseApk
Creating configuration releaseProvided
Creating configuration releaseWearApp
Creating configuration releaseAnnotationProcessor
Creating configuration testReleaseCompile
Creating configuration testReleaseApk
Creating configuration testReleaseProvided
Creating configuration testReleaseWearApp
Creating configuration testReleaseAnnotationProcessor
Parsing the SDK, no caching allowed
Parsing /opt/android-sdk-linux/add-ons/addon-google_apis-google-15/package.xml
Parsing /opt/android-sdk-linux/add-ons/addon-google_apis-google-16/package.xml
Parsing /opt/android-sdk-linux/add-ons/addon-google_apis-google-17/package.xml
Parsing /opt/android-sdk-linux/add-ons/addon-google_apis-google-18/package.xml
Parsing /opt/android-sdk-linux/add-ons/addon-google_apis-google-19/package.xml
Parsing /opt/android-sdk-linux/add-ons/addon-google_apis-google-21/package.xml
Parsing /opt/android-sdk-linux/add-ons/addon-google_apis-google-22/package.xml
Parsing /opt/android-sdk-linux/add-ons/addon-google_apis-google-23/package.xml
Parsing /opt/android-sdk-linux/add-ons/addon-google_apis-google-24/package.xml
Parsing /opt/android-sdk-linux/add-ons/addon-google_gdk-google-19/package.xml
Parsing /opt/android-sdk-linux/build-tools/28.0.2/package.xml
Parsing /opt/android-sdk-linux/docs/package.xml
Parsing /opt/android-sdk-linux/extras/android/m2repository/package.xml
Parsing /opt/android-sdk-linux/extras/google/auto/package.xml
Parsing /opt/android-sdk-linux/extras/google/google_play_services/package.xml
Parsing /opt/android-sdk-linux/extras/google/instantapps/package.xml
Parsing /opt/android-sdk-linux/extras/google/m2repository/package.xml
Parsing /opt/android-sdk-linux/extras/google/market_apk_expansion/package.xml
Parsing /opt/android-sdk-linux/extras/google/market_licensing/package.xml
Parsing /opt/android-sdk-linux/extras/google/simulators/package.xml
Parsing /opt/android-sdk-linux/extras/google/webdriver/package.xml
Parsing /opt/android-sdk-linux/platform-tools/package.xml
Parsing /opt/android-sdk-linux/platforms/android-10/package.xml
Parsing /opt/android-sdk-linux/platforms/android-11/package.xml
Parsing /opt/android-sdk-linux/platforms/android-12/package.xml
Parsing /opt/android-sdk-linux/platforms/android-13/package.xml
Parsing /opt/android-sdk-linux/platforms/android-14/package.xml
Parsing /opt/android-sdk-linux/platforms/android-15/package.xml
Parsing /opt/android-sdk-linux/platforms/android-16/package.xml
Parsing /opt/android-sdk-linux/platforms/android-17/package.xml
Parsing /opt/android-sdk-linux/platforms/android-18/package.xml
Parsing /opt/android-sdk-linux/platforms/android-19/package.xml
Parsing /opt/android-sdk-linux/platforms/android-20/package.xml
Parsing /opt/android-sdk-linux/platforms/android-21/package.xml
Parsing /opt/android-sdk-linux/platforms/android-22/package.xml
Parsing /opt/android-sdk-linux/platforms/android-23/package.xml
Parsing /opt/android-sdk-linux/platforms/android-24/package.xml
Parsing /opt/android-sdk-linux/platforms/android-25/package.xml
Parsing /opt/android-sdk-linux/platforms/android-26/package.xml
Parsing /opt/android-sdk-linux/platforms/android-27/package.xml
Parsing /opt/android-sdk-linux/platforms/android-28/package.xml
Parsing /opt/android-sdk-linux/platforms/android-7/package.xml
Parsing /opt/android-sdk-linux/platforms/android-8/package.xml
Parsing /opt/android-sdk-linux/platforms/android-9/package.xml
Parsing /opt/android-sdk-linux/tools/package.xml
Parsing /opt/android-sdk-linux/add-ons/addon-google_apis-google-15/package.xml
Parsing /opt/android-sdk-linux/add-ons/addon-google_apis-google-16/package.xml
Parsing /opt/android-sdk-linux/add-ons/addon-google_apis-google-17/package.xml
Parsing /opt/android-sdk-linux/add-ons/addon-google_apis-google-18/package.xml
Parsing /opt/android-sdk-linux/add-ons/addon-google_apis-google-19/package.xml
Parsing /opt/android-sdk-linux/add-ons/addon-google_apis-google-21/package.xml
Parsing /opt/android-sdk-linux/add-ons/addon-google_apis-google-22/package.xml
Parsing /opt/android-sdk-linux/add-ons/addon-google_apis-google-23/package.xml
Parsing /opt/android-sdk-linux/add-ons/addon-google_apis-google-24/package.xml
Parsing /opt/android-sdk-linux/add-ons/addon-google_gdk-google-19/package.xml
Parsing /opt/android-sdk-linux/build-tools/28.0.2/package.xml
Parsing /opt/android-sdk-linux/docs/package.xml
Parsing /opt/android-sdk-linux/extras/android/m2repository/package.xml
Parsing /opt/android-sdk-linux/extras/google/auto/package.xml
Parsing /opt/android-sdk-linux/extras/google/google_play_services/package.xml
Parsing /opt/android-sdk-linux/extras/google/instantapps/package.xml
Parsing /opt/android-sdk-linux/extras/google/m2repository/package.xml
Parsing /opt/android-sdk-linux/extras/google/market_apk_expansion/package.xml
Parsing /opt/android-sdk-linux/extras/google/market_licensing/package.xml
Parsing /opt/android-sdk-linux/extras/google/simulators/package.xml
Parsing /opt/android-sdk-linux/extras/google/webdriver/package.xml
Parsing /opt/android-sdk-linux/platform-tools/package.xml
Parsing /opt/android-sdk-linux/platforms/android-10/package.xml
Parsing /opt/android-sdk-linux/platforms/android-11/package.xml
Parsing /opt/android-sdk-linux/platforms/android-12/package.xml
Parsing /opt/android-sdk-linux/platforms/android-13/package.xml
Parsing /opt/android-sdk-linux/platforms/android-14/package.xml
Parsing /opt/android-sdk-linux/platforms/android-15/package.xml
Parsing /opt/android-sdk-linux/platforms/android-16/package.xml
Parsing /opt/android-sdk-linux/platforms/android-17/package.xml
Parsing /opt/android-sdk-linux/platforms/android-18/package.xml
Parsing /opt/android-sdk-linux/platforms/android-19/package.xml
Parsing /opt/android-sdk-linux/platforms/android-20/package.xml
Parsing /opt/android-sdk-linux/platforms/android-21/package.xml
Parsing /opt/android-sdk-linux/platforms/android-22/package.xml
Parsing /opt/android-sdk-linux/platforms/android-23/package.xml
Parsing /opt/android-sdk-linux/platforms/android-24/package.xml
Parsing /opt/android-sdk-linux/platforms/android-25/package.xml
Parsing /opt/android-sdk-linux/platforms/android-26/package.xml
Parsing /opt/android-sdk-linux/platforms/android-27/package.xml
Parsing /opt/android-sdk-linux/platforms/android-28/package.xml
Parsing /opt/android-sdk-linux/platforms/android-7/package.xml
Parsing /opt/android-sdk-linux/platforms/android-8/package.xml
Parsing /opt/android-sdk-linux/platforms/android-9/package.xml
Parsing /opt/android-sdk-linux/tools/package.xml
Parsing /opt/android-sdk-linux/add-ons/addon-google_apis-google-15/package.xml
Parsing /opt/android-sdk-linux/add-ons/addon-google_apis-google-16/package.xml
Parsing /opt/android-sdk-linux/add-ons/addon-google_apis-google-17/package.xml
Parsing /opt/android-sdk-linux/add-ons/addon-google_apis-google-18/package.xml
Parsing /opt/android-sdk-linux/add-ons/addon-google_apis-google-19/package.xml
Parsing /opt/android-sdk-linux/add-ons/addon-google_apis-google-21/package.xml
Parsing /opt/android-sdk-linux/add-ons/addon-google_apis-google-22/package.xml
Parsing /opt/android-sdk-linux/add-ons/addon-google_apis-google-23/package.xml
Parsing /opt/android-sdk-linux/add-ons/addon-google_apis-google-24/package.xml
Parsing /opt/android-sdk-linux/add-ons/addon-google_gdk-google-19/package.xml
Parsing /opt/android-sdk-linux/build-tools/28.0.2/package.xml
Parsing /opt/android-sdk-linux/docs/package.xml
Parsing /opt/android-sdk-linux/extras/android/m2repository/package.xml
Parsing /opt/android-sdk-linux/extras/google/auto/package.xml
Parsing /opt/android-sdk-linux/extras/google/google_play_services/package.xml
Parsing /opt/android-sdk-linux/extras/google/instantapps/package.xml
Parsing /opt/android-sdk-linux/extras/google/m2repository/package.xml
Parsing /opt/android-sdk-linux/extras/google/market_apk_expansion/package.xml
Parsing /opt/android-sdk-linux/extras/google/market_licensing/package.xml
Parsing /opt/android-sdk-linux/extras/google/simulators/package.xml
Parsing /opt/android-sdk-linux/extras/google/webdriver/package.xml
Parsing /opt/android-sdk-linux/platform-tools/package.xml
Parsing /opt/android-sdk-linux/platforms/android-10/package.xml
Parsing /opt/android-sdk-linux/platforms/android-11/package.xml
Parsing /opt/android-sdk-linux/platforms/android-12/package.xml
Parsing /opt/android-sdk-linux/platforms/android-13/package.xml
Parsing /opt/android-sdk-linux/platforms/android-14/package.xml
Parsing /opt/android-sdk-linux/platforms/android-15/package.xml
Parsing /opt/android-sdk-linux/platforms/android-16/package.xml
Parsing /opt/android-sdk-linux/platforms/android-17/package.xml
Parsing /opt/android-sdk-linux/platforms/android-18/package.xml
Parsing /opt/android-sdk-linux/platforms/android-19/package.xml
Parsing /opt/android-sdk-linux/platforms/android-20/package.xml
Parsing /opt/android-sdk-linux/platforms/android-21/package.xml
Parsing /opt/android-sdk-linux/platforms/android-22/package.xml
Parsing /opt/android-sdk-linux/platforms/android-23/package.xml
Parsing /opt/android-sdk-linux/platforms/android-24/package.xml
Parsing /opt/android-sdk-linux/platforms/android-25/package.xml
Parsing /opt/android-sdk-linux/platforms/android-26/package.xml
Parsing /opt/android-sdk-linux/platforms/android-27/package.xml
Parsing /opt/android-sdk-linux/platforms/android-28/package.xml
Parsing /opt/android-sdk-linux/platforms/android-7/package.xml
Parsing /opt/android-sdk-linux/platforms/android-8/package.xml
Parsing /opt/android-sdk-linux/platforms/android-9/package.xml
Parsing /opt/android-sdk-linux/tools/package.xml

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> You have not accepted the license agreements of the following SDK components:
  [Android SDK Build-Tools 25.0.1].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED

Total time: 14.957 secs
Stopped 0 compiler daemon(s).
root@gem-01:~/android#

**Comment by benhylau** [comment]
You don't have NDK or SDK. See:

>./install_debug: 3: ./install_debug: ndk-build: not found

>You have not accepted the license agreements of the following SDK components:

**Comment by vikulin** [comment]
Yes, I understand the issue but I can't resolve it.

2018-08-12 19:35 GMT+03:00 Benedict Lau <notifications@github.com>:

**Comment by sssemil** [comment]
Install Android NDK and add it to PATH.

**Comment by vikulin** [comment]
Hmm, is that automated script and it should do all such stuff by itself?

2018-08-12 20:09 GMT+03:00 Emil Suleymanov <notifications@github.com>:

**Comment by sssemil** [comment]
Not NDK, please, read https://github.com/hyperboria/android/tree/develop#installation.

**Comment by vikulin** [comment]
Done. Seeing following:

root@gem-01:~/android# ./install_debug
Android NDK: WARNING: APP_PLATFORM android-23 is higher than
android:minSdkVersion 1 in src/main//AndroidManifest.xml. NDK binaries will
*not* be compatible with devices older than android-23. See
https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md
for more information.
Android NDK: WARNING: APP_STL stlport_static is deprecated and will be
removed in the next release. Please switch to either c++_static or
c++_shared. See https://developer.android.com/ndk/guides/cpp-support.html
for more information.
Android NDK: The armeabi ABI is no longer supported. Use armeabi-v7a.
Android NDK: NDK Application 'local' targets unknown ABI(s): armeabi mips

Android NDK: Please fix the APP_ABI definition in
src/main//jni/Application.mk
/root/android-ndk-r17b/build/core/setup-app.mk:79: *** Android NDK:
Aborting    .  Stop.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> You have not accepted the license agreements of the following SDK
components:
  [Android SDK Build-Tools 25.0.1].
  Before building your project, you need to accept the license agreements
and complete the installation of the missing components using the Android
Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one
workstation to another, go to
http://d.android.com/r/studio-ui/export-licenses.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or
--debug option to get more log output.

BUILD FAILED

Total time: 15.391 secs
root@gem-01:~/android#

2018-08-12 20:16 GMT+03:00 Emil Suleymanov <notifications@github.com>:

**Comment by sssemil** [comment]
You need r11c version, not r17b.
